version: '2'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:latest
    network_mode: host
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - /opt/esdata:/usr/share/elasticsearch/data
    command: -Enetwork.bind_host=0.0.0.0
  kibana:
    container_name: kibana
    image: kibana:latest
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    network_mode: host
    links:
      - elasticsearch
  logger:
    image: alpine:latest
    volumes:
      - $PWD/bin:/root/bin
      - $PWD/logs:/logs
    entrypoint: /bin/sh -c "/root/bin/logger -out /logs/mylog.log"