version: '2'
services:
  elasticsearch:
    image: elasticsearch:latest
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
  kibana:
    image: kibana:latest
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  logger:
    image: alpine:latest
    volumes:
      - $PWD/bin:/root/bin
      - $PWD/logs:/logs
    entrypoint: /bin/sh -c "/root/bin/logger -out /logs/mylog.log"