version: '2'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:5.2.0
    network_mode: host
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - /opt/esdata:/usr/share/elasticsearch/data
    command: -Enetwork.bind_host=0.0.0.0
  kibana:
    container_name: kibana
    image: kibana:5.2.0
    depends_on:
      - elasticsearch
    network_mode: host
    restart: always
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://192.168.66.100:9200