version: '2'
services:
  elasticsearch:
    image: elasticsearch:latest
    command: [
      -Des.threadpool.index.queue_size=100000]
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - /opt/esdata:/usr/share/elasticsearch/data
  kibana:
    image: kibana:latest
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200