version: '2'

services:

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:5.2.0
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /opt/esdata:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: kibana:5.2.0
    depends_on:
      - elasticsearch
    networks:
      - elk
    restart: always
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"

networks:

  elk:
    driver: bridge
